[package]
name = "contract-test-app"
documentation.workspace = true
authors.workspace = true
version.workspace = true
license.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
sails-rtl.workspace = true
gstd.workspace = true